### ISSUE TITLE
Multiple Data Monitoring Banners observed after DM20 timeout

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#21]
Joe Kartje saw a “temporal” error from the V2 driving tests at each speed interval and restarted function C [Track Monitor Completion Status] after receiving each such error. Could this account for the multiple data monitoring banners?

**Comment by gumbelmj** [comment]
This error was caused by a NPE pointer exception as a result of not receiving the DM5 from the engine after clearing the DTCs.

2017-06-06 11:21:24.897 SEVERE net.soliddesign.iumpr.controllers.Controller lambda$getRunnable$0 Error
java.lang.NullPointerException: temporal
at java.util.Objects.requireNonNull(Objects.java:228)
at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1741)
at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
at net.soliddesign.iumpr.modules.DateTimeModule.format(DateTimeModule.java:37)
at net.soliddesign.iumpr.controllers.MonitorCompletionController.run(MonitorCompletionController.java:147)
at net.soliddesign.iumpr.controllers.Controller.lambda$getRunnable$0(Controller.java:425)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by gumbelmj** [comment]
Changed the logic to insist the engine respond to DM5, DM20, DM26 and DM21 requests.  If the engine doesn't respond after three attempts, "No Response" is recorded. If a DM5 is no returned, the process will cease thus preventing this error in the future.
