### ISSUE TITLE
NPE as a result of no initial DM5

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#29]
When monitoring completion status, upon reporting, the initial DM5 time from the engine is required.  Because the engine did not supply at DM5 after the DTCs were cleared a NullPointerException resulted:

2017-06-06 11:21:24.897 SEVERE net.soliddesign.iumpr.controllers.Controller lambda$getRunnable$0 Error
java.lang.NullPointerException: temporal
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1741)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at net.soliddesign.iumpr.modules.DateTimeModule.format(DateTimeModule.java:37)
	at net.soliddesign.iumpr.controllers.MonitorCompletionController.run(MonitorCompletionController.java:147)
	at net.soliddesign.iumpr.controllers.Controller.lambda$getRunnable$0(Controller.java:425)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gumbelmj** [comment]
Duplicate of #21
